server:
    port: 8080
    address: 192.168.202.62

#logging:
#    level.org.springframework.web: debug

spring:
    application:
        name: loes-prod
    datasource:
        url: jdbc:mysql://localhost:3306/loes_new
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
    data:
        redis:
            host: localhost
            port: 6380

mybatis:
    configuration:
        map-underscore-to-camel-case: true

snowflake:
    machine-bit: 0
    data-center-bit: 0

jwt:
    key: loes
    duration-hours: 24
